// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCum-q79PQz5QY0TiN-A92pfasx2chPVTg',
    appId: '1:1038806454938:web:b4bdabea4c584154bd4523',
    messagingSenderId: '1038806454938',
    projectId: 'e-architect-f72f8',
    authDomain: 'e-architect-f72f8.firebaseapp.com',
    databaseURL: 'https://e-architect-f72f8-default-rtdb.firebaseio.com',
    storageBucket: 'e-architect-f72f8.appspot.com',
    measurementId: 'G-P88REXH0CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj6zqrqhixkdoV7GUudt0rr42weIOQwu0',
    appId: '1:1038806454938:android:ac2b50c88d9e90f8bd4523',
    messagingSenderId: '1038806454938',
    projectId: 'e-architect-f72f8',
    databaseURL: 'https://e-architect-f72f8-default-rtdb.firebaseio.com',
    storageBucket: 'e-architect-f72f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu1gcEF3uM-HgSIixj8kdGPg57Y__y6zc',
    appId: '1:1038806454938:ios:310ac578de0c9ebabd4523',
    messagingSenderId: '1038806454938',
    projectId: 'e-architect-f72f8',
    databaseURL: 'https://e-architect-f72f8-default-rtdb.firebaseio.com',
    storageBucket: 'e-architect-f72f8.appspot.com',
    iosClientId: '1038806454938-9kkg7gnstuk107rombjl01op56i20luq.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyPanel',
  );
}
